version: '3'
services:
  frontend:
    container_name: nextjs
    build: frontend
    ports:
      - "3000:3000"

  backend:
    container_name: fastapi
    build: backend
    ports:
      - "8000:8000"