services:
  - type: web
    name: frontend
    env: docker
    repo: https://github.com/defton290/JudokasConnect
    dockerfilePath: frontend/Dockerfile
    contextPath: frontend
    envVars:
      - key: PORT
        value: 3000
    plan: free
    autoDeploy: true

  - type: web
    name: backend
    env: docker
    repo: https://github.com/defton290/JudokasConnect
    dockerfilePath: backend/Dockerfile
    contextPath: backend
    envVars:
      - key: PORT
        value: 8000
    plan: free
    autoDeploy: true
