services:
  - type: web
    name: frontend
    env: docker
    repo: https://github.com/defton290/JudokasConnect
    dockerfilePath: frontend/Dockerfile
    buildCommand: ""
    startCommand: "npm run dev"
    envVars:
      - key: PORT
        value: 3000
    plan: free
    autoDeploy: true

  - type: web
    name: backend
    env: docker
    repo: https://github.com/defton290/JudokasConnect
    dockerfilePath: backend/Dockerfile
    buildCommand: ""
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: PORT
        value: 8000
    plan: free
    autoDeploy: true
